INSERT INTO assets (id, type, name, version, path, metadata)
VALUES
    (
        'char_halku_v1',
        'character',
        'Halku',
        '1.0.0',
        'res://assets/characters/halku/halku.tscn',
        '{"role":"seller","voice":"voice_cheerful_male_v1","default_animation":"anim_idle_v1","dialogue_profile":{"speech_style":"hustler","sentence_length":"short","humor_level":0.8,"aggression":0.2,"vocabulary":"simple","catchphrase_probability":0.2,"catchphrases":["Arre bhaiya","Asli maal hai"]}}'
    ),
    (
        'char_policeman_v1',
        'character',
        'Policeman',
        '1.0.0',
        'res://assets/characters/policeman/policeman.tscn',
        '{"role":"authority","voice":"voice_stern_male_v1","default_animation":"anim_idle_v1","dialogue_profile":{"speech_style":"authoritative","sentence_length":"short","humor_level":0.1,"aggression":0.8,"vocabulary":"formal","catchphrase_probability":0.1,"catchphrases":["Oye","Kanoon ke haath"]}}'
    ),
    (
        'scene_village_market_v1',
        'scene',
        'Village Market',
        '1.0.0',
        'res://assets/scenes/village_market/village_market.tscn',
        '{"vertical_safe_area":true,"interaction_zones":[{"id":"market_stall","type":"selling_zone","priority":100,"capacity":1,"adjacent":["stall_front"]},{"id":"stall_front","type":"customer_zone","priority":80,"capacity":2,"adjacent":["scene_center"]},{"id":"scene_center","type":"neutral_zone","priority":50,"capacity":10,"adjacent":["entrance","tree_area"]},{"id":"tree_area","type":"rest_zone","priority":20,"capacity":3,"adjacent":["scene_center"]},{"id":"entrance","type":"entry_zone","priority":10,"capacity":5,"adjacent":["scene_center"]}]}'
    ),
    (
        'prop_bottle_v1',
        'prop',
        'Bottle',
        '1.0.0',
        'res://assets/props/bottle/bottle.tscn',
        '{"portable":true}'
    ),
    (
        'anim_idle_v1',
        'animation',
        'Idle',
        '1.0.0',
        'res://assets/animations/humanoid/idle.res',
        '{"loop":true,"category":"neutral","duration":2.0}'
    ),
    (
        'anim_walk_v1',
        'animation',
        'Walk',
        '1.0.0',
        'res://assets/animations/humanoid/walk.res',
        '{"loop":true,"category":"locomotion","duration":1.5}'
    ),
    (
        'anim_talk_v1',
        'animation',
        'Talk',
        '1.0.0',
        'res://assets/animations/humanoid/talk.res',
        '{"loop":true,"category":"dialogue","duration":2.5}'
    ),
    (
        'anim_run_v1',
        'animation',
        'Run',
        '1.0.0',
        'res://assets/animations/humanoid/run.res',
        '{"loop":true,"category":"locomotion","duration":1.2}'
    ),
    (
        'anim_point_v1',
        'animation',
        'Point',
        '1.0.0',
        'res://assets/animations/humanoid/point.res',
        '{"loop":false,"category":"gesture","duration":1.0}'
    ),
    (
        'anim_pickup_v1',
        'animation',
        'Pickup',
        '1.0.0',
        'res://assets/animations/humanoid/pickup.res',
        '{"loop":false,"category":"interaction","duration":1.8}'
    ),
    (
        'anim_celebrate_v1',
        'animation',
        'Celebrate',
        '1.0.0',
        'res://assets/animations/humanoid/celebrate.res',
        '{"loop":false,"category":"emotion","duration":2.0}'
    ),
    (
        'anim_laugh_v1',
        'animation',
        'Laugh',
        '1.0.0',
        'res://assets/animations/humanoid/laugh.res',
        '{"loop":false,"category":"emotion","duration":1.5}'
    ),
    (
        'anim_inspect_v1',
        'animation',
        'Inspect',
        '1.0.0',
        'res://assets/animations/humanoid/inspect.res',
        '{"loop":false,"category":"interaction","duration":2.0}'
    ),
    (
        'anim_argue_v1',
        'animation',
        'Argue',
        '1.0.0',
        'res://assets/animations/humanoid/argue.res',
        '{"loop":true,"category":"dialogue","duration":2.5}'
    ),
    (
        'voice_cheerful_male_v1',
        'voice',
        'Cheerful Male',
        '1.0.0',
        'registry://voices/cheerful_male',
        '{"style":"cheerful","gender":"male"}'
    ),
    (
        'voice_stern_male_v1',
        'voice',
        'Stern Male',
        '1.0.0',
        'registry://voices/stern_male',
        '{"style":"stern","gender":"male"}'
    ),
    (
        'cam_wide_v1',
        'camera',
        'Wide',
        '1.0.0',
        NULL,
        '{"preset":"wide","goal":"show_introduction","vertical_framing":true}'
    ),
    (
        'cam_medium_v1',
        'camera',
        'Medium',
        '1.0.0',
        NULL,
        '{"preset":"medium","goal":"show_dialogue","vertical_framing":true}'
    ),
    (
        'cam_closeup_v1',
        'camera',
        'Closeup',
        '1.0.0',
        NULL,
        '{"preset":"closeup","goal":"show_reaction","vertical_framing":true}'
    ),
    (
        'cam_tracking_v1',
        'camera',
        'Tracking',
        '1.0.0',
        NULL,
        '{"preset":"tracking","goal":"show_chase","vertical_framing":true}'
    ),
    (
        'cam_reaction_v1',
        'camera',
        'Reaction',
        '1.0.0',
        NULL,
        '{"preset":"reaction","goal":"show_reaction","vertical_framing":true}'
    ),
    (
        'cam_hero_v1',
        'camera',
        'Hero',
        '1.0.0',
        NULL,
        '{"preset":"hero","goal":"show_introduction","vertical_framing":true}'
    ),
    (
        'cam_dialogue_v1',
        'camera',
        'Dialogue',
        '1.0.0',
        NULL,
        '{"preset":"dialogue","goal":"show_dialogue","vertical_framing":true}'
    ),
    (
        'cam_shot_reverse_shot_v1',
        'camera',
        'Shot Reverse Shot',
        '1.0.0',
        NULL,
        '{"preset":"shot_reverse_shot","goal":"show_argument","vertical_framing":true}'
    ),
    (
        'intent_sell_product_v1',
        'intent',
        'Sell Product',
        '1.0.0',
        NULL,
        '{"description":"Actor presents or offers a product to nearby characters.","camera_goal":"show_dialogue","default_emotion":"confident","distance":"near","animations":["anim_pickup_v1","anim_point_v1","anim_talk_v1"]}'
    ),
    (
        'intent_question_v1',
        'intent',
        'Question',
        '1.0.0',
        NULL,
        '{"description":"Actor questions a target character.","camera_goal":"show_dialogue","default_emotion":"suspicious","distance":"near","animations":["anim_talk_v1"]}'
    ),
    (
        'intent_inspect_v1',
        'intent',
        'Inspect',
        '1.0.0',
        NULL,
        '{"description":"Actor closely observes a target character or prop.","camera_goal":"show_reaction","default_emotion":"focused","distance":"contact","animations":["anim_inspect_v1"]}'
    ),
    (
        'intent_greet_v1',
        'intent',
        'Greet',
        '1.0.0',
        NULL,
        '{"description":"Actor greets a target character.","camera_goal":"show_dialogue","default_emotion":"happy","distance":"near","animations":["anim_talk_v1"]}'
    ),
    (
        'intent_argue_v1',
        'intent',
        'Argue',
        '1.0.0',
        NULL,
        '{"description":"Actor argues with a target character.","camera_goal":"show_argument","default_emotion":"angry","distance":"confrontation","animations":["anim_argue_v1"]}'
    ),
    (
        'intent_run_away_v1',
        'intent',
        'Run Away',
        '1.0.0',
        NULL,
        '{"description":"Actor flees from a target character.","camera_goal":"show_chase","default_emotion":"scared","distance":"far","animations":["anim_run_v1"]}'
    ),
    (
        'intent_chase_v1',
        'intent',
        'Chase',
        '1.0.0',
        NULL,
        '{"description":"Actor chases a target character.","camera_goal":"show_chase","default_emotion":"angry","distance":"near","animations":["anim_run_v1"]}'
    ),
    (
        'intent_celebrate_v1',
        'intent',
        'Celebrate',
        '1.0.0',
        NULL,
        '{"description":"Actor celebrates.","camera_goal":"show_reaction","default_emotion":"happy","distance":"near","animations":["anim_celebrate_v1"]}'
    ),
    (
        'intent_laugh_v1',
        'intent',
        'Laugh',
        '1.0.0',
        NULL,
        '{"description":"Actor laughs.","camera_goal":"show_reaction","default_emotion":"happy","distance":"near","animations":["anim_laugh_v1"]}'
    )
ON CONFLICT (id) DO NOTHING;
